# Generated by Django 4.2.6 on 2023-11-13 10:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('project', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='project',
            name='bob1_1',
        ),
        migrations.RemoveField(
            model_name='project',
            name='bob1_2',
        ),
        migrations.RemoveField(
            model_name='project',
            name='bob1_3',
        ),
        migrations.RemoveField(
            model_name='project',
            name='bob2_1',
        ),
        migrations.RemoveField(
            model_name='project',
            name='bob2_2',
        ),
        migrations.RemoveField(
            model_name='project',
            name='bob2_3',
        ),
        migrations.RemoveField(
            model_name='project',
            name='bob3_1',
        ),
        migrations.RemoveField(
            model_name='project',
            name='bob3_2',
        ),
        migrations.RemoveField(
            model_name='project',
            name='bob3_3',
        ),
    ]
